language: cpp
compiler: gcc
os: linux
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
      - libboost-dev
      - mpi-default-bin
      - mpi-default-dev
      - libgmp-dev
      - libopenmpi-dev
      - autotools-dev
      - automake
      - libug-dev
      - libmetis-dev
      - libparmetis-dev
cache:
  directories:
    - /build

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - sudo source ${TRAVIS_BUILD_DIR}/.ci/setup_travis.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - cp config.opts_example config.opts
  - sed -i -e '/^PETSCPATH/d' -e '/ZOLTANPATH/d' config.opts && sed -i -e '1 a PETSCPATH="/usr/lib"' config.opts
  - ./INSTALL.sh
  - cd tests
  - sh ./initial_test.sh
  - cd ../data
  # now download nn mesh and try it 
  - wget https://zenodo.org/record/1313709/files/NNmesh_small.tar.gz
  - tar xf NNmesh_small.tar.gz
  - cp parameter parameterBU
  - cp standardparams standardparamsBU
  - cd ../tests
  - travis_wait 30 sh ./nn_test.sh

after_failure:
  - echo "########## PETSc installation log ##########"
  - cat /home/travis/build/EIT-team/PEITS/PEITS_root/petsc/arch-linux2-c-opt/lib/petsc/conf/make.log
  - echo "########## PETSc configuration log ##########"
  - cat /home/travis/build/EIT-team/PEITS/PEITS_root/petsc/arch-linux2-c-opt/lib/petsc/conf/configure.log
