language: cpp
compiler: gcc
os: linux
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
      - libboost-dev
      - mpi-default-bin
      - mpi-default-dev
      - libgmp-dev
      - libopenmpi-dev
      - autotools-dev
      - automake
      - libug-dev
      - libmetis-dev
      - libparmetis-dev
cache:
  directories:
    - /$HOME/ci-helper

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - source ${TRAVIS_BUILD_DIR}/.ci/setup_travis.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - cp config.opts_example config.opts
  - sed -i -e '/^PETSCPATH/d' -e '/^ZOLTANPATH/d' config.opts
  - sed -i -e "1 a PETSCPATH=${ci_path}/usr/lib" -e "1 a ZOLTANPATH=${ci_path}/usr" config.opts
  - cat config.opts
  - ./INSTALL.sh
  - cd tests
  - sh ./initial_test.sh
  - travis_wait 30 sh ./nn_test.sh
