language: bash
sudo: required

before_install:
  - sudo apt-get -qq update
  - |
    sudo apt-get install -y libblas-dev liblapack-dev gfortran libboost-dev \
                            mpi-default-bin mpi-default-dev libgmp-dev libopenmpi-dev \
                            autotools-dev automake libug-dev gfortran \
                            libmetis-dev libparmetis-dev
  
install:
  - mkdir PEITS_root
  - cd PEITS_root

  # Download, build and install PETSc
  - git clone -b maint https://bitbucket.org/petsc/petsc
  - cd petsc
  - mkdir petscBUILD
  - git checkout 8695de0
  - |
    ./configure --prefix=/usr \
                --with-x=0 --with-debugging=0 -CFLAGS="-O3 -DNDEBUG -ffast-math" \
                --with-parmetis=1 --with-hypre=1 --download-hypre=yes \
                --with-superlu_dist=1 --download-superlu_dist=yes \
                --with-mumps=1 --download-mumps=yes \
                --with-ml=1 --download-ml=yes \
                --with-metis=1 \
                --download-scalapack=yes --download-blacs=yes && \
    make all test && make install

  # Download, build and install Zoltan
  - cd $TRAVIS_BUILD_DIR/PEITS_root
  - wget http://www.cs.sandia.gov/~kddevin/Zoltan_Distributions/zoltan_distrib_v3.83.tar.gz
  - tar xf zoltan_distrib_v3.83.tar.gz --warning=no-unknown-keyword
  - mkdir Zoltan_v3.83/BUILD_DIR
  - cd Zoltan_v3.83/BUILD_DIR
  - |
    ../configure --prefix=/usr \
                 --with-parmetis --with-parmetis-incdir=/usr/include/ --with-parmetis-libdir=/usr/lib/ && \
    make everything && \
    make install
  
script:
  - cd $TRAVIS_BUILD_DIR
  - cp config.opts_example config.opts
  - sed -i -e '/^PETSCPATH/d' -e '/ZOLTANPATH/d' -e '1 a PETSCPATH="/usr/lib"' config.opts
  - ./INSTALL.sh
  - cd tests
  - sh ./initial_test.sh
  - cd ../data
  # now download nn mesh and try it 
  - wget https://zenodo.org/record/1313709/files/NNmesh_small.tar.gz
  - tar xf NNmesh_small.tar.gz
  - cp parameter parameterBU
  - cp standardparams standardparamsBU
  - cd ../tests
  - travis_wait 30 sh ./nn_test.sh
  - travis_wait 30 sh ./nn_test.sh


